$$ &&
	$$('grt', {
		xprefix: 'https://xaidozy.github.io/grt',
		data: [
			'Snow_Dayy;The Tunnel',
			'China_X_Piano;a^徐梦圆;p^China-X(钢琴)',
			'y^Enchanted_Forest',
			'Yo^Bye_Bye_Lover',
			'p^Invisible_Umbrella;a^MoreanP',
			'Cyi4xia4si1xiang1;a^MoreanP;y^忆夏思乡',
			'p^Escape_This_Moment;LightScape',
			'Hyperpop;Glitchcore',
			'p^Rokoy_City',
			'Yo^Autumn;a^Kawaii',
			'Aftermath;Adam Lambert',
			'Y^Bgm_Sky_Block',
			'A^Breezy_Street',
			'Aqua_Start',
			'R^Cloudy0a33',
			'R^Space0a33',
			'R^Storm0a33',
			'a^Infinity_Heaven;HyuN',
			'Je411v7pu',
			'Cwei4zhi1;;未知',
			'Bloody_A60;r^praayy',
			'y^I_Love_You_3k_Times;云上丝路',
			'y^Pleasant_Advanture',
			'Po^Carrier32',
			'g^Original_Soundtrack',
			'Background4',
			'p^Bgm_Sky_Wars',
			'o^CharlieXCX;cozin',
			'go^Em_Trap',
			'p^At_The_Edge;空野リンジ&千坂',
			'Yo^Come_Home;a^DDRKirby(ISQ)',
			'y^Never_Forget_Me;Senbeii',
			'a^Funky_Stars;Quazar',
			'Carly_Paige;3Lau Touch',
			'Csheng4xia4de0sheng4xia4;TFDUCKS;P^剩下的盛夏',
			'Sad;Егор Иксов',
			'r^Anan_Ryoko;Refrain',
			'Pararrayos;a^Valentin',
			'Spark;r^Ronald Jenkees',
			'Cxing1cha2hui4;Kuroba;a^星茶会',
			'Quiet3',
			'Cyue4;郁可唯Yisa;月',
			'p^Neon_Dreams;Lofi',
			'Heart_Beat;Morrow',
			'a^Decoy_World;Intercom',
			'Cgu1zhu2yi2meng4;a^徐梦圆;孤竹遗梦',
			'Far_Away_Piano;五月的钢琴声;p^Far Away(钢琴)',
			'Brighter_Skies;LightScape',
			'p^A_New_Start;Rameses',
			'Cjin3li3;The Script;锦鲤',
		],
	});
