$$ &&
	$$('grt', {
		xprefix: 'https://xaidozy.github.io/grt',
		data: [
			'Snow_Dayy;The Tunnel;y',
			'China_X_Piano;a^徐梦圆;p;China-X(钢琴)',
			'Enchanted_Forest;;y',
			'Bye_Bye_Lover;;Y',
			'Invisible_Umbrella;a^MoreanP;p',
			'Cyi4xia4si1xiang1;a^MoreanP;y;忆夏思乡',
			'Escape_This_Moment;LightScape;p',
			'Hyperpop;Glitchcore;a',
			'Rokoy_City;;p',
			'Autumn;a^Kawaii;Y',
			'Aftermath;Adam Lambert;y',
			'Bgm_Sky_Block;;Y',
			'Breezy_Street;;y',
			'Aqua_Start;;a',
			'Cloudy0a33;;r',
			'Space0a33;;r',
			'Storm0a33;;r',
			'Infinity_Heaven;HyuN;a',
			'Je411v7pu;;y',
			'Cwei4zhi1;;y;未知',
			'Bloody_A60;r^praayy;a',
			'I_Love_You_3k_Times;云上丝路;y',
			'Pleasant_Advanture;;y',
			'Carrier32;;W',
			'Original_Soundtrack',
			'Background4',
			'Bgm_Sky_Wars;;p',
			'CharlieXCX;cozin;Y',
			'Em_Trap;;y',
			'At_The_Edge;空野リンジ&千坂;p',
			'Come_Home;a^DDRKirby(ISQ);Y',
			'Never_Forget_Me;Senbeii;y',
			'Funky_Stars;Quazar;a',
			'Carly_Paige;3Lau Touch;Y',
			'Csheng4xia4de0sheng4xia4;TFDUCKS;p;剩下的盛夏',
			'Sad;Егор Иксов;y',
			'Anan_Ryoko;Refrain;r',
			'Pararrayos;a^Valentin;Y',
			'Spark;r^Ronald Jenkees;a',
			'Cxing1cha2hui4;Kuroba;a;星茶会',
			'Quiet3;;W',
			'Cyue4;郁可唯Yisa;p;月',
			'Neon_Dreams;Lofi;p',
			'Heart_Beat;Morrow;y',
			'Decoy_World;Intercom;a',
			'Cgu1zhu2yi2meng4;a^徐梦圆;p;孤竹遗梦',
			'Far_Away_Piano;五月的钢琴声;p;Far Away(钢琴)',
			'Brighter_Skies;LightScape;p',
			'A_New_Start;Rameses;p',
			'Cjin3li3;The Script;Y;锦鲤',
		],
	});
